mines:


loot-tables:
  STONE:
    - material: COBBLESTONE
      chance: 1.0
      amount: 1
      xp: 1.0
      currency: 0.1
      sound: block.stone.hit
    - material: EMERALD
      chance: 0.01
      amount: 1
      xp: 10.0
      currency: 5.0
      sound: entity.experience_orb.pickup

  COAL_ORE:
    - material: COAL
      chance: 1.0
      amount: 2
      xp: 2.0
      currency: 0.2
      sound: block.stone.break
    - material: EMERALD
      chance: 0.005
      amount: 1
      xp: 20.0
      currency: 10.0
      sound: entity.experience_orb.pickup

  IRON_ORE:
    - material: RAW_IRON
      chance: 1.0
      amount: 1
      xp: 4.0
      currency: 0.5
      sound: block.anvil.place

  GOLD_ORE:
    - material: RAW_GOLD
      chance: 1.0
      amount: 1
      xp: 6.0
      currency: 1.0
      sound: block.anvil.place

  DIAMOND_ORE:
    - material: DIAMOND
      chance: 1.0
      amount: 1
      xp: 25.0
      currency: 20.0
      sound: entity.player.levelup

  EMERALD_ORE:
    - material: EMERALD
      chance: 1.0
      amount: 1
      xp: 30.0
      currency: 25.0
      sound: entity.player.levelup

  LAPIS_ORE:
    - material: LAPIS_LAZULI
      chance: 1.0
      amount: 4
      xp: 5.0
      currency: 2.0
      sound: entity.item.pickup

  REDSTONE_ORE:
    - material: REDSTONE
      chance: 1.0
      amount: 4
      xp: 6.0
      currency: 2.0
      sound: entity.item.pickup

  NETHER_QUARTZ_ORE:
    - material: QUARTZ
      chance: 1.0
      amount: 1
      xp: 3.0
      currency: 1.0
      sound: block.basalt.hit

  ANCIENT_DEBRIS:
    - material: NETHERITE_SCRAP
      chance: 1.0
      amount: 1
      xp: 50.0
      currency: 100.0
      sound: block.respawn_anchor.ambient


block-prices:
  # Basics
  COBBLESTONE: 5
  STONE: 10
  GRANITE: 10
  DIORITE: 10
  ANDESITE: 10
  DIRT: 5
  COARSE_DIRT: 05
  GRASS_BLOCK: 07
  SAND: 05
  RED_SAND: 05
  GRAVEL: 05
  CLAY: 10

  # Ores
  COAL_ORE: 50
  IRON_ORE: 100
  COPPER_ORE: 75
  LAPIS_ORE: 150
  REDSTONE_ORE: 200
  GOLD_ORE: 300
  EMERALD_ORE: 800
  DIAMOND_ORE: 1000
  NETHER_QUARTZ_ORE: 100
  NETHER_GOLD_ORE: 200
  ANCIENT_DEBRIS: 1500

  # Nether & End
  NETHERRACK: 2
  BASALT: 10
  BLACKSTONE: 10
  SOUL_SAND: 5
  SOUL_SOIL: 5
  END_STONE: 10
  OBSIDIAN: 200
  CRYING_OBSIDIAN: 300

  # Logs (all types)
  OAK_LOG: 20
  SPRUCE_LOG: 20
  BIRCH_LOG: 20
  JUNGLE_LOG: 20
  ACACIA_LOG: 20
  DARK_OAK_LOG: 20
  MANGROVE_LOG: 20
  CHERRY_LOG: 20
  CRIMSON_STEM: 20
  WARPED_STEM: 20

  # Crafted / Processed blocks
  OAK_PLANKS: 25
  STONE_BRICKS: 30
  BRICKS: 40
  GLASS: 40
  SMOOTH_STONE: 30
  QUARTZ_BLOCK: 30
  IRON_BLOCK: 900
  GOLD_BLOCK: 2700
  DIAMOND_BLOCK: 9000
  EMERALD_BLOCK: 7200
  NETHERITE_BLOCK: 13500
