name: Prisonkb
version: 1.0.0
main: org.cludivers.prisonkb.Prisonkb
description: Prison plugin
author: kz2wd
api-version: '1.21.8'
commands:
  stats:
    description: Show your prison stats (rank, xp, currency, prestige)
    usage: /stats
  sellall:
    description: Sell all your mined items
    usage: /sellall
  mine:
    description: Teleport to a mine
    usage: /mine <name>
  spawn:
    description: Teleport to the spawn
    usage: /spawn
  rankup:
    description: Rank up
    usage: /rankup
permissions:
  prison.use:
    default: true
  prison.admin:
    default: op